name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps
        run: npm install

      - name: Run unit tests with coverage
        run: npm run test:ci

  performance:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: grafana/setup-k6-action@v1

      - name: Run k6 ramp test
        run: k6 run tests/k6/ramp.js

      - name: Run k6 spike test
        run: k6 run tests/k6/spike.js

      - name: Run k6 soak test
        run: k6 run tests/k6/soak.js
