name: CI - Backend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ci-backend-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Mostrar estructura (debug)
        run: |
          pwd
          ls -la

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: package-lock.json   # <-- en la raíz

      - name: Install deps
        run: npm ci

      - name: Unit tests (fail <90% coverage)
        run: npm test -- --ci --coverage
        env:
          CI: "true"

      - name: Guardar coverage
        if: always()
        run: |
          mkdir -p artifacts
          if [ -d coverage ]; then cp -r coverage artifacts/coverage; fi
          npm test -- --coverage --coverageReporters="text-summary" --passWithNoTests | tee artifacts/test-summary.txt || true

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage-and-summary
          path: |
            artifacts/**
            coverage/**
          if-no-files-found: warn

  performance:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' || (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'perf'))
    steps:
      - uses: actions/checkout@v4

      - name: Install k6
        run: |
          sudo apt-get update
          sudo apt-get install -y gnupg ca-certificates
          sudo mkdir -p /etc/apt/keyrings
          curl -fsSL https://dl.k6.io/key.gpg | sudo gpg --dearmor -o /etc/apt/keyrings/k6.gpg
          echo "deb [signed-by=/etc/apt/keyrings/k6.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install -y k6

      - name: Ensure artifacts dir
        run: mkdir -p artifacts

      - name: Ramp
        run: k6 run tests/k6/ramp.js --summary-export artifacts/ramp-summary.json
        env:
          BASE_URL: ${{ secrets.BACKEND_BASE_URL }}

      - name: Spike
        run: k6 run tests/k6/spike.js --summary-export artifacts/spike-summary.json
        env:
          BASE_URL: ${{ secrets.BACKEND_BASE_URL }}

      - name: Soak
        run: k6 run tests/k6/soak.js --summary-export artifacts/soak-summary.json
        env:
          BASE_URL: ${{ secrets.BACKEND_BASE_URL }}

      - name: Upload k6
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: k6-summaries
          path: artifacts/*.json
          if-no-files-found: warn
